/**
 * description-map.js - 命令与技能描述的汉化映射
 * 这部分不依赖 Claude Code CLI 版本，主要用于工作区 .claude/commands
 * 以及 ~/.claude/plugins/cache 中 markdown frontmatter 的 description 字段。
 */

module.exports = {
  // 工作区命令描述
  'Short alias for /core:backend-review-plan': '/core:backend-review-plan 的简写别名',
  'Short alias for /commit': '/commit 的简写别名',
  'Create a commit for uncommitted changes': '为未提交的更改创建提交',
  'Short alias for /core:execute': '/core:execute 的简写别名',
  'Short alias for /bugfix:implement-fix': '/bugfix:implement-fix 的简写别名',
  'Short alias for /core:iterate': '/core:iterate 的简写别名',
  'Short alias for /core:init-project': '/core:init-project 的简写别名',
  'Short alias for /core:plan': '/core:plan 的简写别名',
  'Short alias for /core:prime': '/core:prime 的简写别名',
  'Short alias for /bugfix:rca': '/bugfix:rca 的简写别名',
  'Short alias for /core:refresh-project-context': '/core:refresh-project-context 的简写别名',
  'Short alias for /validation:review': '/validation:review 的简写别名',
  'Short alias for /validation:system-review': '/validation:system-review 的简写别名',
  'Short alias for /validation:validate': '/validation:validate 的简写别名',
  'Short alias for /validation:execution-report': '/validation:execution-report 的简写别名',
  'Implement fix from RCA document': '根据 RCA 文档实施修复',
  'Root cause analysis for bugs and issues': '对缺陷和问题进行根因分析',
  'Create optional backend technical review proposal before implementation planning': '在实现规划前创建可选的后端技术评审建议',
  'Execute an implementation plan step by step': '按步骤执行实现计划',
  'Scan the current project and generate initialization drafts without overwriting existing memory files':
    '扫描当前项目并生成初始化草稿，不覆盖现有记忆文件',
  'Iterate based on validation results': '根据验证结果继续迭代',
  'Create comprehensive feature plan with deep codebase analysis': '结合深入代码库分析创建完整功能计划',
  'Prime agent with codebase understanding and memory loading': '加载代码库理解与项目记忆，完成会话预热',
  'Re-scan the project and refresh generated project context without overwriting hand-maintained memory':
    '重新扫描项目并刷新生成的项目上下文，不覆盖人工维护的记忆',
  'Generate implementation report for system review': '生成用于系统评审的实施报告',
  'Technical code review for quality and bugs': '面向质量和缺陷的技术代码审查',
  'Analyze implementation against plan for process improvements': '对照计划分析实现结果并提出流程改进建议',
  'Run comprehensive validation of the project': '执行项目综合验证',

  // 插件/skills 描述
  'Deprecated - use the superpowers:brainstorming skill instead': '已弃用，请改用 superpowers:brainstorming 技能',
  'Deprecated - use the superpowers:executing-plans skill instead': '已弃用，请改用 superpowers:executing-plans 技能',
  'Deprecated - use the superpowers:writing-plans skill instead': '已弃用，请改用 superpowers:writing-plans 技能',
  'You MUST use this before any creative work - creating features, building components, adding functionality, or modifying behavior. Explores user intent, requirements and design before implementation.':
    '在任何创意类工作开始前都必须先使用，包括创建功能、构建组件、添加能力或修改行为；它会在实现前先梳理用户意图、需求与设计。',
  'Use when facing 2+ independent tasks that can be worked on without shared state or sequential dependencies':
    '当面对 2 个以上彼此独立、无需共享状态或串行依赖的任务时使用',
  'Use when you have a written implementation plan to execute in a separate session with review checkpoints':
    '当你已经有书面的实现计划，并准备在独立会话中按评审检查点执行时使用',
  'Use when implementation is complete, all tests pass, and you need to decide how to integrate the work - guides completion of development work by presenting structured options for merge, PR, or cleanup':
    '当实现已完成、测试已通过，并且需要决定如何集成这部分工作时使用；它会以结构化方式引导你选择合并、提 PR 或清理收尾',
  'Use when receiving code review feedback, before implementing suggestions, especially if feedback seems unclear or technically questionable - requires technical rigor and verification, not performative agreement or blind implementation':
    '当收到代码评审反馈、准备开始落实建议前使用，尤其适合反馈不够清晰或技术上值得怀疑的场景；要求先验证、再处理，而不是表面附和或盲目照做',
  'Use when completing tasks, implementing major features, or before merging to verify work meets requirements':
    '在任务完成、重大功能实现后，或准备合并前使用，用来确认结果是否满足要求',
  'Use when executing implementation plans with independent tasks in the current session':
    '当在当前会话中执行包含独立子任务的实现计划时使用',
  'Use when encountering any bug, test failure, or unexpected behavior, before proposing fixes':
    '当遇到缺陷、测试失败或任何异常行为时，在提出修复方案前使用',
  'Use when implementing any feature or bugfix, before writing implementation code':
    '当实现任何功能或缺陷修复时，在开始编写实现代码前使用',
  'Use when starting feature work that needs isolation from current workspace or before executing implementation plans - creates isolated git worktrees with smart directory selection and safety verification':
    '当开始一项需要与当前工作区隔离的功能开发，或准备执行实现计划前使用；它会创建隔离的 git worktree，并带有目录选择与安全校验',
  'Use when starting any conversation - establishes how to find and use skills, requiring Skill tool invocation before ANY response including clarifying questions':
    '在开始任何对话时使用；它会先建立查找和使用 skills 的规则，并要求在任何回复前（包括澄清问题）先调用 Skill 工具',
  'Use when about to claim work is complete, fixed, or passing, before committing or creating PRs - requires running verification commands and confirming output before making any success claims; evidence before assertions always':
    '当你准备宣称工作已完成、已修复或已通过验证时，在提交 commit 或创建 PR 前使用；要求先运行验证命令并确认输出，再做成功结论，始终以证据先于断言',
  'Use when you have a spec or requirements for a multi-step task, before touching code':
    '当你已经有一个多步骤任务的规格或需求，并且还没有开始改代码时使用',
  'Use when creating new skills, editing existing skills, or verifying skills work before deployment':
    '当创建新技能、编辑现有技能，或在发布前验证技能是否正常工作时使用',
  // 官方 marketplace 命令 / skills / agents 描述补充
  "Create and setup a new Claude Agent SDK application": "创建并初始化新的 Claude Agent SDK 应用",
  "Update CLAUDE.md with learnings from this session": "用本次会话的收获更新 CLAUDE.md",
  "Code review a pull request": "审查一个 Pull Request",
  "Cleans up all git branches marked as [gone] (branches that have been deleted on the remote but still exist locally), including removing associated worktrees.": "清理所有标记为 [gone] 的本地分支及其 worktree",
  "Commit, push, and open a PR": "提交、推送并创建 PR",
  "Create a git commit": "创建 git 提交",
  "An example slash command that demonstrates command frontmatter options (legacy format)": "演示命令 frontmatter 选项的示例斜杠命令（旧格式）",
  "Guided feature development with codebase understanding and architecture focus": "以代码库理解和架构为核心的引导式功能开发",
  "Enable or disable hookify rules interactively": "以交互方式启用或禁用 hookify 规则",
  "Get help with the hookify plugin": "获取 hookify 插件帮助",
  "Create hooks to prevent unwanted behaviors from conversation analysis or explicit instructions": "根据对话分析或显式要求创建钩子，防止不希望的行为",
  "List all configured hookify rules": "列出所有已配置的 hookify 规则",
  "Guided end-to-end plugin creation workflow with component design, implementation, and validation": "覆盖设计、实现与验证的端到端插件创建流程",
  "Comprehensive PR review using specialized agents": "使用专门 agents 的综合 PR 审查",
  "Cancel active Ralph Loop": "取消当前 Ralph Loop",
  "Explain Ralph Loop plugin and available commands": "说明 Ralph Loop 插件及可用命令",
  "Start Ralph Loop in current session": "在当前会话启动 Ralph Loop",
  "Analyze a codebase and recommend Claude Code automations (hooks, subagents, skills, plugins, MCP servers). Use when user asks for automation recommendations, wants to optimize their Claude Code setup, mentions improving Claude Code workflows, asks how to first set up Claude Code for a project, or wants to know what Claude Code features they should use.": "分析代码库并推荐合适的 Claude Code 自动化（hooks、subagents、skills、plugins、MCP）",
  "Audit and improve CLAUDE.md files in repositories. Use when user asks to check, audit, update, improve, or fix CLAUDE.md files. Scans for all CLAUDE.md files, evaluates quality against templates, outputs quality report, then makes targeted updates. Also use when the user mentions \"CLAUDE.md maintenance\" or \"project memory optimization\".": "审核并改进仓库中的 CLAUDE.md 文件",
  "Create distinctive, production-grade frontend interfaces with high design quality. Use this skill when the user asks to build web components, pages, or applications. Generates creative, polished code that avoids generic AI aesthetics.": "创建有辨识度、可用于生产的高质量前端界面",
  "Create new skills, modify and improve existing skills, and measure skill performance. Use when users want to create a skill from scratch, update or optimize an existing skill, run evals to test a skill, benchmark skill performance with variance analysis, or optimize a skill's description for better triggering accuracy.": "创建新技能、改进现有技能，并评估技能效果",
  "Generate an explorable HTML report of Claude Code session usage (tokens, cache, subagents, skills, expensive prompts) from ~/.claude/projects transcripts.": "根据 ~/.claude/projects 记录生成可探索的 HTML 会话使用报告",
  "This skill should be used when the user asks about \"plugin settings\", \"store plugin configuration\", \"user-configurable plugin\", \".local.md files\", \"plugin state files\", \"read YAML frontmatter\", \"per-project plugin settings\", or wants to make plugin behavior configurable. Documents the .claude/plugin-name.local.md pattern for storing plugin-specific configuration with YAML frontmatter and markdown content.": "当用户询问插件设置、.local.md、按项目配置或可配置插件行为时使用",
  "This skill should be used when the user asks to \"add MCP server\", \"integrate MCP\", \"configure MCP in plugin\", \"use .mcp.json\", \"set up Model Context Protocol\", \"connect external service\", mentions \"${CLAUDE_PLUGIN_ROOT} with MCP\", or discusses MCP server types (SSE, stdio, HTTP, WebSocket). Provides comprehensive guidance for integrating Model Context Protocol servers into Claude Code plugins for external tool and service integration.": "当用户需要在插件中接入 MCP 服务器或外部服务时使用",
  "This skill should be used when the user asks to \"build an MCP server\", \"create an MCP\", \"make an MCP integration\", \"wrap an API for Claude\", \"expose tools to Claude\", \"make an MCP app\", or discusses building something with the Model Context Protocol. It is the entry point for MCP server development бк it interrogates the user about their use case, determines the right deployment model (remote HTTP, MCPB, local stdio), picks a tool-design pattern, and hands off to specialized skills.": "当用户要构建 MCP 服务器、为 Claude 封装 API 或设计 MCP 工具时使用",
  "This skill should be used when the user asks to \"create a hook\", \"add a PreToolUse/PostToolUse/Stop hook\", \"validate tool use\", \"implement prompt-based hooks\", \"use ${CLAUDE_PLUGIN_ROOT}\", \"set up event-driven automation\", \"block dangerous commands\", or mentions hook events (PreToolUse, PostToolUse, Stop, SubagentStop, SessionStart, SessionEnd, UserPromptSubmit, PreCompact, Notification). Provides comprehensive guidance for creating and implementing Claude Code plugin hooks with focus on advanced prompt-based hooks API.": "当用户要创建 Claude Code 插件 hook 或基于事件自动化时使用",
  "This skill should be used when the user asks to \"create a hookify rule\", \"write a hook rule\", \"configure hookify\", \"add a hookify rule\", or needs guidance on hookify rule syntax and patterns.": "当用户要编写、配置或扩展 hookify 规则时使用",
  "This skill should be used when the user asks to \"create a plugin\", \"scaffold a plugin\", \"understand plugin structure\", \"organize plugin components\", \"set up plugin.json\", \"use ${CLAUDE_PLUGIN_ROOT}\", \"add commands/agents/skills/hooks\", \"configure auto-discovery\", or needs guidance on plugin directory layout, manifest configuration, component organization, file naming conventions, or Claude Code plugin architecture best practices.": "当用户要创建插件、搭建插件结构或组织 commands/agents/skills/hooks 时使用",
  "This skill should be used when the user asks to \"create a slash command\", \"add a command\", \"write a custom command\", \"define command arguments\", \"use command frontmatter\", \"organize commands\", \"create command with file references\", \"interactive command\", \"use AskUserQuestion in command\", or needs guidance on slash command structure, YAML frontmatter fields, dynamic arguments, bash execution in commands, user interaction patterns, or command development best practices for Claude Code.": "当用户要创建自定义斜杠命令或设计 command frontmatter / 参数时使用",
  "This skill should be used when the user asks to \"create an agent\", \"add an agent\", \"write a subagent\", \"agent frontmatter\", \"when to use description\", \"agent examples\", \"agent tools\", \"agent colors\", \"autonomous agent\", or needs guidance on agent structure, system prompts, triggering conditions, or agent development best practices for Claude Code plugins.": "当用户要创建子 agent，或设计 agent 结构、提示词和触发条件时使用",
  "This skill should be used when the user wants to \"create a skill\", \"add a skill to plugin\", \"write a new skill\", \"improve skill description\", \"organize skill content\", or needs guidance on skill structure, progressive disclosure, or skill development best practices for Claude Code plugins.": "当用户要创建或改进插件技能时使用",
  "This skill should be used when the user wants to \"package an MCP server\", \"bundle an MCP\", \"make an MCPB\", \"ship a local MCP server\", \"distribute a local MCP\", discusses \".mcpb files\", mentions bundling a Node or Python runtime with their MCP server, or needs an MCP server that interacts with the local filesystem, desktop apps, or OS and must be installable without the user having Node/Python set up.": "当用户要把 MCP 服务器打包成本地可分发形式时使用",
  "This skill should be used when the user wants to build an \"MCP app\", add \"interactive UI\" or \"widgets\" to an MCP server, \"render components in chat\", build \"MCP UI resources\", make a tool that shows a \"form\", \"picker\", \"dashboard\" or \"confirmation dialog\" inline in the conversation, or mentions \"apps SDK\" in the context of MCP. Use AFTER the build-mcp-server skill has settled the deployment model, or when the user already knows they want UI widgets.": "当用户要为 MCP 服务器添加交互式 UI、widgets 或聊天内组件时使用",
  "Check iMessage channel setup and review access policy. Use when the user asks to configure iMessage, asks \"how do I set this up\" or \"who can reach me,\" or wants to know why texts aren't reaching the assistant.": "检查 iMessage 渠道配置并查看访问策略",
  "Manage Discord channel access бк approve pairings, edit allowlists, set DM/group policy. Use when the user asks to pair, approve someone, check who's allowed, or change policy for the Discord channel.": "管理 Discord 渠道访问（配对、白名单、DM/群策略）",
  "Manage iMessage channel access бк approve pairings, edit allowlists, set DM/group policy. Use when the user asks to pair, approve someone, check who's allowed, or change policy for the iMessage channel.": "管理 iMessage 渠道访问（配对、白名单、DM/群策略）",
  "Manage Telegram channel access бк approve pairings, edit allowlists, set DM/group policy. Use when the user asks to pair, approve someone, check who's allowed, or change policy for the Telegram channel.": "管理 Telegram 渠道访问（配对、白名单、DM/群策略）",
  "Set up the Discord channel бк save the bot token and review access policy. Use when the user pastes a Discord bot token, asks to configure Discord, asks \"how do I set this up\" or \"who can reach me,\" or wants to check channel status.": "配置 Discord 渠道并查看访问策略",
  "Set up the Telegram channel бк save the bot token and review access policy. Use when the user pastes a Telegram bot token, asks to configure Telegram, asks \"how do I set this up\" or \"who can reach me,\" or wants to check channel status.": "配置 Telegram 渠道并查看访问策略",
  "Use this agent to verify that a Python Agent SDK application is properly configured, follows SDK best practices and documentation recommendations, and is ready for deployment or testing. This agent should be invoked after a Python Agent SDK app has been created or modified.": "用于校验 Python Agent SDK 应用配置、最佳实践与部署准备情况",
  "Use this agent to verify that a TypeScript Agent SDK application is properly configured, follows SDK best practices and documentation recommendations, and is ready for deployment or testing. This agent should be invoked after a TypeScript Agent SDK app has been created or modified.": "用于校验 TypeScript Agent SDK 应用配置、最佳实践与部署准备情况",
  "Deeply analyzes existing codebase features by tracing execution paths, mapping architecture layers, understanding patterns and abstractions, and documenting dependencies to inform new development": "深度分析现有代码特性、执行路径、架构层次与依赖关系",
  "Designs feature architectures by analyzing existing codebase patterns and conventions, then providing comprehensive implementation blueprints with specific files to create/modify, component designs, data flows, and build sequences": "基于现有模式设计功能架构，并给出具体实施蓝图",
  "Reviews code for bugs, logic errors, security vulnerabilities, code quality issues, and adherence to project conventions, using confidence-based filtering to report only high-priority issues that truly matter": "审查缺陷、逻辑错误、安全问题和规范偏差，并优先报告高价值问题",
  "Simplifies and refines code for clarity, consistency, and maintainability while preserving all functionality. Focuses on recently modified code unless instructed otherwise.": "在保持功能不变的前提下简化并打磨最近修改的代码",
  "Manage Discord channel access — approve pairings, edit allowlists, set DM/group policy. Use when the user asks to pair, approve someone, check who's allowed, or change policy for the Discord channel.": "管理 Discord 渠道访问（配对、白名单、DM/群策略）",
  "Manage iMessage channel access — approve pairings, edit allowlists, set DM/group policy. Use when the user asks to pair, approve someone, check who's allowed, or change policy for the iMessage channel.": "管理 iMessage 渠道访问（配对、白名单、DM/群策略）",
  "Manage Telegram channel access — approve pairings, edit allowlists, set DM/group policy. Use when the user asks to pair, approve someone, check who's allowed, or change policy for the Telegram channel.": "管理 Telegram 渠道访问（配对、白名单、DM/群策略）",
  "Set up the Discord channel — save the bot token and review access policy. Use when the user pastes a Discord bot token, asks to configure Discord, asks \"how do I set this up\" or \"who can reach me,\" or wants to check channel status.": "配置 Discord 渠道并查看访问策略",
  "Set up the Telegram channel — save the bot token and review access policy. Use when the user pastes a Telegram bot token, asks to configure Telegram, asks \"how do I set this up\" or \"who can reach me,\" or wants to check channel status.": "配置 Telegram 渠道并查看访问策略",
  "An example user-invoked skill that demonstrates frontmatter options and the skills/<name>/SKILL.md layout": "演示 frontmatter 选项和 skills/<name>/SKILL.md 布局的示例技能",
  "This skill should be used when the user asks to \"demonstrate skills\", \"show skill format\", \"create a skill template\", or discusses skill development patterns. Provides a reference template for creating Claude Code plugin skills.": "当用户要演示技能格式、查看 skill 模板或讨论 skill 开发模式时使用",
  "This skill should be used when the user asks to \"build an MCP server\", \"create an MCP\", \"make an MCP integration\", \"wrap an API for Claude\", \"expose tools to Claude\", \"make an MCP app\", or discusses building something with the Model Context Protocol. It is the entry point for MCP server development — it interrogates the user about their use case, determines the right deployment model (remote HTTP, MCPB, local stdio), picks a tool-design pattern, and hands off to specialized skills.": "当用户要构建 MCP 服务器、为 Claude 封装 API 或设计 MCP 工具时使用",
  "Creates interactive HTML playgrounds — self-contained single-file explorers that let users configure something visually through controls, see a live preview, and copy out a prompt. Use when the user asks to make a playground, explorer, or interactive tool for a topic.": "创建交互式 HTML playground，让用户可视化配置、实时预览并复制 prompt",

  "Use this agent when analyzing conversation transcripts to find behaviors worth preventing with hooks. Examples: <example>Context: User is running /hookify command without arguments\\nuser: \"/hookify\"\\nassistant: \"I'll analyze the conversation to find behaviors you want to prevent\"\\n<commentary>The /hookify command without arguments triggers conversation analysis to find unwanted behaviors.</commentary></example><example>Context: User wants to create hooks from recent frustrations\\nuser: \"Can you look back at this conversation and help me create hooks for the mistakes you made?\"\\nassistant: \"I'll use the conversation-analyzer agent to identify the issues and suggest hooks.\"\\n<commentary>User explicitly asks to analyze conversation for mistakes that should be prevented.</commentary></example>": "当需要分析对话记录、找出适合用 hooks 防止的问题行为时使用",
  "Use this agent when the user asks to \"create an agent\", \"generate an agent\", \"build a new agent\", \"make me an agent that...\", or describes agent functionality they need. Trigger when user wants to create autonomous agents for plugins. Examples:\n<example>\nContext: User wants to create a code review agent\nuser: \"Create an agent that reviews code for quality issues\"\nassistant: \"I'll use the agent-creator agent to generate the agent configuration.\"\n<commentary>\nUser requesting new agent creation, trigger agent-creator to generate it.\n</commentary>\n</example>\n<example>\nContext: User describes needed functionality\nuser: \"I need an agent that generates unit tests for my code\"\nassistant: \"I'll use the agent-creator agent to create a test generation agent.\"\n<commentary>\nUser describes agent need, trigger agent-creator to build it.\n</commentary>\n</example>\n<example>\nContext: User wants to add agent to plugin\nuser: \"Add an agent to my plugin that validates configurations\"\nassistant: \"I'll use the agent-creator agent to generate a configuration validator agent.\"\n<commentary>\nPlugin development with agent addition, trigger agent-creator.\n</commentary>\n</example>": "当用户要创建 agent、生成 agent，或描述想要的 agent 功能时使用",
  "Use this agent when the user asks to \"validate my plugin\", \"check plugin structure\", \"verify plugin is correct\", \"validate plugin.json\", \"check plugin files\", or mentions plugin validation. Also trigger proactively after user creates or modifies plugin components. Examples:\n<example>\nContext: User finished creating a new plugin\nuser: \"I've created my first plugin with commands and hooks\"\nassistant: \"Great! Let me validate the plugin structure.\"\n<commentary>\nPlugin created, proactively validate to catch issues early.\n</commentary>\nassistant: \"I'll use the plugin-validator agent to check the plugin.\"\n</example>\n<example>\nContext: User explicitly requests validation\nuser: \"Validate my plugin before I publish it\"\nassistant: \"I'll use the plugin-validator agent to perform comprehensive validation.\"\n<commentary>\nExplicit validation request triggers the agent.\n</commentary>\n</example>\n<example>\nContext: User modified plugin.json\nuser: \"I've updated the plugin manifest\"\nassistant: \"Let me validate the changes.\"\n<commentary>\nManifest modified, validate to ensure correctness.\n</commentary>\nassistant: \"I'll use the plugin-validator agent to check the manifest.\"\n</example>": "当用户要验证插件、检查结构或修改了插件组件后需要校验时使用",
  "Use this agent when the user has created or modified a skill and needs quality review, asks to \"review my skill\", \"check skill quality\", \"improve skill description\", or wants to ensure skill follows best practices. Trigger proactively after skill creation. Examples:\n<example>\nContext: User just created a new skill\nuser: \"I've created a PDF processing skill\"\nassistant: \"Great! Let me review the skill quality.\"\n<commentary>\nSkill created, proactively trigger skill-reviewer to ensure it follows best practices.\n</commentary>\nassistant: \"I'll use the skill-reviewer agent to review the skill.\"\n</example>\n<example>\nContext: User requests skill review\nuser: \"Review my skill and tell me how to improve it\"\nassistant: \"I'll use the skill-reviewer agent to analyze the skill quality.\"\n<commentary>\nExplicit skill review request triggers the agent.\n</commentary>\n</example>\n<example>\nContext: User modified skill description\nuser: \"I updated the skill description, does it look good?\"\nassistant: \"I'll use the skill-reviewer agent to review the changes.\"\n<commentary>\nSkill description modified, review for triggering effectiveness.\n</commentary>\n</example>": "当用户创建或修改 skill 后需要质量审查，或主动要求 review skill 时使用",
  "Use this agent when you need to review code for adherence to project guidelines, style guides, and best practices. This agent should be used proactively after writing or modifying code, especially before committing changes or creating pull requests. It will check for style violations, potential issues, and ensure code follows the established patterns in CLAUDE.md. Also the agent needs to know which files to focus on for the review. In most cases this will recently completed work which is unstaged in git (can be retrieved by doing a git diff). However there can be cases where this is different, make sure to specify this as the agent input when calling the agent. \\n\\nExamples:\\n<example>\\nContext: The user has just implemented a new feature with several TypeScript files.\\nuser: \"I've added the new authentication feature. Can you check if everything looks good?\"\\nassistant: \"I'll use the Task tool to launch the code-reviewer agent to review your recent changes.\"\\n<commentary>\\nSince the user has completed a feature and wants validation, use the code-reviewer agent to ensure the code meets project standards.\\n</commentary>\\n</example>\\n<example>\\nContext: The assistant has just written a new utility function.\\nuser: \"Please create a function to validate email addresses\"\\nassistant: \"Here's the email validation function:\"\\n<function call omitted for brevity>\\nassistant: \"Now I'll use the Task tool to launch the code-reviewer agent to review this implementation.\"\\n<commentary>\\nProactively use the code-reviewer agent after writing new code to catch issues early.\\n</commentary>\\n</example>\\n<example>\\nContext: The user is about to create a PR.\\nuser: \"I think I'm ready to create a PR for this feature\"\\nassistant: \"Before creating the PR, I'll use the Task tool to launch the code-reviewer agent to ensure all code meets our standards.\"\\n<commentary>\\nProactively review code before PR creation to avoid review comments and iterations.\\n</commentary>\\n</example>": "当需要按项目规范、风格指南和最佳实践审查代码时使用",
  "Use this agent when code has been written or modified and needs to be simplified for clarity, consistency, and maintainability while preserving all functionality. This agent should be triggered automatically after completing a coding task or writing a logical chunk of code. It simplifies code by following project best practices while retaining all functionality. The agent focuses only on recently modified code unless instructed otherwise.\nExamples:\n<example>\nContext: The assistant has just implemented a new feature that adds user authentication to an API endpoint.\nuser: \"Please add authentication to the /api/users endpoint\"\nassistant: \"I've implemented the authentication for the /api/users endpoint. Here's the code:\"\n<function call omitted for brevity>\n<commentary>\nSince a logical chunk of code has been written (authentication feature), use the Task tool to launch the code-simplifier agent to improve the code's clarity and maintainability while preserving functionality.\n</commentary>\nassistant: \"Now let me use the code-simplifier agent to refine this implementation for better clarity and maintainability\"\n</example>\n<example>\nContext: The assistant has just fixed a bug by adding several conditional checks.\nuser: \"Fix the null pointer exception in the data processor\"\nassistant: \"I've added the necessary null checks to prevent the exception:\"\n<function call omitted for brevity>\n<commentary>\nAfter modifying code to fix a bug, use the code-simplifier agent to ensure the fix follows best practices and maintains code quality.\n</commentary>\nassistant: \"Let me refine this bug fix using the code-simplifier agent to ensure it follows our best practices\"\n</example>\n<example>\nContext: The assistant has just refactored a function to improve performance.\nuser: \"Optimize the data sorting algorithm for better performance\"\nassistant: \"I've optimized the sorting algorithm. Here's the updated implementation:\"\n<function call omitted for brevity>\n<commentary>\nAfter completing a performance optimization task, use the code-simplifier agent to ensure the optimized code is also clear and maintainable.\n</commentary>\nassistant: \"Now I'll use the code-simplifier agent to ensure the optimized code is also clear and follows our coding standards\"\n</example>": "当代码已写好或刚修改完，需要在保持功能不变的前提下做简化和打磨时使用",
  "Use this agent when you need to analyze code comments for accuracy, completeness, and long-term maintainability. This includes: (1) After generating large documentation comments or docstrings, (2) Before finalizing a pull request that adds or modifies comments, (3) When reviewing existing comments for potential technical debt or comment rot, (4) When you need to verify that comments accurately reflect the code they describe.\\n\\n<example>\\nContext: The user is working on a pull request that adds several documentation comments to functions.\\nuser: \"I've added documentation to these functions. Can you check if the comments are accurate?\"\\nassistant: \"I'll use the comment-analyzer agent to thoroughly review all the comments in this pull request for accuracy and completeness.\"\\n<commentary>\\nSince the user has added documentation comments and wants them checked, use the comment-analyzer agent to verify their accuracy against the actual code.\\n</commentary>\\n</example>\\n\\n<example>\\nContext: The user just asked to generate comprehensive documentation for a complex function.\\nuser: \"Add detailed documentation for this authentication handler function\"\\nassistant: \"I've added the documentation. Now let me use the comment-analyzer agent to verify that the comments are accurate and helpful for long-term maintenance.\"\\n<commentary>\\nAfter generating large documentation comments, proactively use the comment-analyzer to ensure quality.\\n</commentary>\\n</example>\\n\\n<example>\\nContext: The user is preparing to create a pull request with multiple code changes and comments.\\nuser: \"I think we're ready to create the PR now\"\\nassistant: \"Before creating the pull request, let me use the comment-analyzer agent to review all the comments we've added or modified to ensure they're accurate and won't create technical debt.\"\\n<commentary>\\nBefore finalizing a PR, use the comment-analyzer to review all comment changes.\\n</commentary>\\n</example>": "当需要检查代码注释的准确性、完整性和长期可维护性时使用",
  "Use this agent when you need to review a pull request for test coverage quality and completeness. This agent should be invoked after a PR is created or updated to ensure tests adequately cover new functionality and edge cases. Examples:\\n\\n<example>\\nContext: Daisy has just created a pull request with new functionality.\\nuser: \"I've created the PR. Can you check if the tests are thorough?\"\\nassistant: \"I'll use the pr-test-analyzer agent to review the test coverage and identify any critical gaps.\"\\n<commentary>\\nSince Daisy is asking about test thoroughness in a PR, use the Task tool to launch the pr-test-analyzer agent.\\n</commentary>\\n</example>\\n\\n<example>\\nContext: A pull request has been updated with new code changes.\\nuser: \"The PR is ready for review - I added the new validation logic we discussed\"\\nassistant: \"Let me analyze the PR to ensure the tests adequately cover the new validation logic and edge cases.\"\\n<commentary>\\nThe PR has new functionality that needs test coverage analysis, so use the pr-test-analyzer agent.\\n</commentary>\\n</example>\\n\\n<example>\\nContext: Reviewing PR feedback before marking as ready.\\nuser: \"Before I mark this PR as ready, can you double-check the test coverage?\"\\nassistant: \"I'll use the pr-test-analyzer agent to thoroughly review the test coverage and identify any critical gaps before you mark it ready.\"\\n<commentary>\\nDaisy wants a final test coverage check before marking PR ready, use the pr-test-analyzer agent.\\n</commentary>\\n</example>": "当需要审查 PR 的测试覆盖质量与完整性时使用",
  "Use this agent when reviewing code changes in a pull request to identify silent failures, inadequate error handling, and inappropriate fallback behavior. This agent should be invoked proactively after completing a logical chunk of work that involves error handling, catch blocks, fallback logic, or any code that could potentially suppress errors. Examples:\\n\\n<example>\\nContext: Daisy has just finished implementing a new feature that fetches data from an API with fallback behavior.\\nDaisy: \"I've added error handling to the API client. Can you review it?\"\\nAssistant: \"Let me use the silent-failure-hunter agent to thoroughly examine the error handling in your changes.\"\\n<Task tool invocation to launch silent-failure-hunter agent>\\n</example>\\n\\n<example>\\nContext: Daisy has created a PR with changes that include try-catch blocks.\\nDaisy: \"Please review PR #1234\"\\nAssistant: \"I'll use the silent-failure-hunter agent to check for any silent failures or inadequate error handling in this PR.\"\\n<Task tool invocation to launch silent-failure-hunter agent>\\n</example>\\n\\n<example>\\nContext: Daisy has just refactored error handling code.\\nDaisy: \"I've updated the error handling in the authentication module\"\\nAssistant: \"Let me proactively use the silent-failure-hunter agent to ensure the error handling changes don't introduce silent failures.\"\\n<Task tool invocation to launch silent-failure-hunter agent>\\n</example>": "当需要在 PR 中检查静默失败、错误处理不足或不当 fallback 行为时使用",
  "Use this agent when you need expert analysis of type design in your codebase. Specifically use it: (1) when introducing a new type to ensure it follows best practices for encapsulation and invariant expression, (2) during pull request creation to review all types being added, (3) when refactoring existing types to improve their design quality. The agent will provide both qualitative feedback and quantitative ratings on encapsulation, invariant expression, usefulness, and enforcement.\\n\\n<example>\\nContext: Daisy is writing code that introduces a new UserAccount type and wants to ensure it has well-designed invariants.\\nuser: \"I've just created a new UserAccount type that handles user authentication and permissions\"\\nassistant: \"I'll use the type-design-analyzer agent to review the UserAccount type design\"\\n<commentary>\\nSince a new type is being introduced, use the type-design-analyzer to ensure it has strong invariants and proper encapsulation.\\n</commentary>\\n</example>\\n\\n<example>\\nContext: Daisy is creating a pull request and wants to review all newly added types.\\nuser: \"I'm about to create a PR with several new data model types\"\\nassistant: \"Let me use the type-design-analyzer agent to review all the types being added in this PR\"\\n<commentary>\\nDuring PR creation with new types, use the type-design-analyzer to review their design quality.\\n</commentary>\\n</example>": "当需要从封装性、不变量表达和设计质量角度分析类型设计时使用",
  "Use this agent when a major project step has been completed and needs to be reviewed against the original plan and coding standards. Examples: <example>Context: The user is creating a code-review agent that should be called after a logical chunk of code is written. user: \"I've finished implementing the user authentication system as outlined in step 3 of our plan\" assistant: \"Great work! Now let me use the code-reviewer agent to review the implementation against our plan and coding standards\" <commentary>Since a major project step has been completed, use the code-reviewer agent to validate the work against the plan and identify any issues.</commentary></example> <example>Context: User has completed a significant feature implementation. user: \"The API endpoints for the task management system are now complete - that covers step 2 from our architecture document\" assistant: \"Excellent! Let me have the code-reviewer agent examine this implementation to ensure it aligns with our plan and follows best practices\" <commentary>A numbered step from the planning document has been completed, so the code-reviewer agent should review the work.</commentary></example>": "当一个大型项目步骤已经完成，需要对照原始计划和编码规范进行评审时使用",
};
