/**
 * keyword.js - Claude Code 界面汉化关键词映射
 * 合并自 mine-auto-cli-main + cute-claude-hooks
 * 覆盖: 配置面板、命令描述、UI文案、快捷键提示等
 */

const spinnerVerbMap = Object.fromEntries(
  [
    'Accomplishing',
    'Actioning',
    'Actualizing',
    'Architecting',
    'Baking',
    'Beaming',
    "Beboppin'",
    'Befuddling',
    'Billowing',
    'Blanching',
    'Bloviating',
    'Boogieing',
    'Boondoggling',
    'Booping',
    'Bootstrapping',
    'Brewing',
    'Bunning',
    'Burrowing',
    'Calculating',
    'Canoodling',
    'Caramelizing',
    'Cascading',
    'Catapulting',
    'Cerebrating',
    'Channeling',
    'Channelling',
    'Choreographing',
    'Churning',
    'Clauding',
    'Coalescing',
    'Cogitating',
    'Combobulating',
    'Composing',
    'Computing',
    'Concocting',
    'Considering',
    'Contemplating',
    'Cooking',
    'Crafting',
    'Creating',
    'Crunching',
    'Crystallizing',
    'Cultivating',
    'Deciphering',
    'Deliberating',
    'Determining',
    'Dilly-dallying',
    'Discombobulating',
    'Doing',
    'Doodling',
    'Drizzling',
    'Ebbing',
    'Effecting',
    'Elucidating',
    'Embellishing',
    'Enchanting',
    'Envisioning',
    'Evaporating',
    'Fermenting',
    'Fiddle-faddling',
    'Finagling',
    'Flambéing',
    'Flibbertigibbeting',
    'Flowing',
    'Flummoxing',
    'Fluttering',
    'Forging',
    'Forming',
    'Frolicking',
    'Frosting',
    'Gallivanting',
    'Galloping',
    'Garnishing',
    'Generating',
    'Gesticulating',
    'Germinating',
    'Gitifying',
    'Grooving',
    'Gusting',
    'Harmonizing',
    'Hashing',
    'Hatching',
    'Herding',
    'Honking',
    'Hullaballooing',
    'Hyperspacing',
    'Ideating',
    'Imagining',
    'Improvising',
    'Incubating',
    'Inferring',
    'Infusing',
    'Ionizing',
    'Jitterbugging',
    'Julienning',
    'Kneading',
    'Leavening',
    'Levitating',
    'Lollygagging',
    'Manifesting',
    'Marinating',
    'Meandering',
    'Metamorphosing',
    'Misting',
    'Moonwalking',
    'Moseying',
    'Mulling',
    'Mustering',
    'Musing',
    'Nebulizing',
    'Nesting',
    'Newspapering',
    'Noodling',
    'Nucleating',
    'Orbiting',
    'Orchestrating',
    'Osmosing',
    'Perambulating',
    'Percolating',
    'Perusing',
    'Philosophising',
    'Photosynthesizing',
    'Pollinating',
    'Pondering',
    'Pontificating',
    'Pouncing',
    'Precipitating',
    'Prestidigitating',
    'Processing',
    'Proofing',
    'Propagating',
    'Puttering',
    'Puzzling',
    'Quantumizing',
    'Razzle-dazzling',
    'Razzmatazzing',
    'Recombobulating',
    'Reticulating',
    'Roosting',
    'Ruminating',
    'Sautéing',
    'Scampering',
    'Schlepping',
    'Scurrying',
    'Seasoning',
    'Shenaniganing',
    'Shimmying',
    'Simmering',
    'Skedaddling',
    'Sketching',
    'Slithering',
    'Smooshing',
    'Sock-hopping',
    'Spelunking',
    'Spinning',
    'Sprouting',
    'Stewing',
    'Sublimating',
    'Swirling',
    'Swooping',
    'Symbioting',
    'Synthesizing',
    'Tempering',
    'Thinking',
    'Thundering',
    'Tinkering',
    'Tomfoolering',
    'Topsy-turvying',
    'Transfiguring',
    'Transmuting',
    'Twisting',
    'Undulating',
    'Unfurling',
    'Unravelling',
    'Vibing',
    'Waddling',
    'Wandering',
    'Warping',
    'Whatchamacalliting',
    'Whirlpooling',
    'Whirring',
    'Whisking',
    'Wibbling',
    'Working',
    'Wrangling',
    'Zesting',
    'Zigzagging',
  ].map(verb => [verb, '处理中']),
);

const rawKeywordMap = {
  'RAW:: to cycle between default mode and auto mode': ' 在默认模式和自动模式之间切换',
  'RAW:: to cycle between default mode, auto-accept edit mode, and plan mode': ' 在默认模式、自动接受编辑模式和计划模式之间切换',
  'RAW:: to paste images from your clipboard': ' 将剪贴板中的图片粘贴进来',
  'RAW::Continue your session in Claude Code Desktop with ': '在 Claude Code Desktop 中继续当前会话：',
  'RAW::Install the Claude GitHub App': '安装 Claude GitHub App',
  'RAW:: for better one-shot answers. Claude thinks it through first.': ' 以获得更好的单次回答。Claude 会先充分思考。',
  'RAW::Working on something tricky? ': '在处理棘手任务？',
  'RAW:: gives better first answers': ' 能给出更好的首轮答案',
  'RAW::For big tasks, tell Claude to ': '处理大型任务时，可以告诉 Claude ',
  'RAW::. They work in parallel and keep your main thread clean.': '。它们会并行工作，并让你的主线程保持清爽。',
  'RAW::Say ': '试着说 ',
  'RAW:: and Claude sends a team. Each one digs deep so nothing gets missed.': '，Claude 就会派出一个团队。每个子代理都会深入处理，尽量不遗漏细节。',
  'RAW:: to run any prompt on a schedule. Set it and forget it.': ' 来按计划定时运行任意提示词。设好后就可以不用管了。',
  'RAW:: runs any prompt on a recurring schedule. Great for monitoring deploys, babysitting PRs, or polling status.':
    ' 可以按周期重复运行任意提示词。很适合监控部署、盯 PR，或轮询状态。',
  'RAW::Share Claude Code and earn ': '分享 Claude Code，可获得 ',
  'RAW:: of extra usage · ': ' 的额外用量 · ',
  'RAW::You have free guest passes to share · ': '你有免费的访客通行证可以分享 · ',
  'RAW:: in extra usage, on us': ' 的额外用量，由我们赠送',
  'RAW::Auth conflict: Using ': '认证冲突：当前使用 ',
  'RAW:: instead of Claude account subscription token. Either unset ': '，而不是 Claude 账户订阅令牌。请取消设置 ',
  'RAW:: instead of Anthropic Console key. Either unset ': '，而不是 Anthropic Console 密钥。请取消设置 ',
  'RAW::, or run `claude /logout`.': '，或执行 `claude /logout`。',
  'RAW::Auth conflict: Both a token (': '认证冲突：同时存在令牌（',
  'RAW::) and an API key (': '）和 API Key（',
  'RAW::) are set. This may lead to unexpected behavior.': '）配置。这可能导致非预期行为。',
  'RAW::· Trying to use ': '· 想使用 ',
  'RAW::? Unset the ANTHROPIC_API_KEY environment variable, or claude /logout then say "No" to the API key approval before login.':
    '？请取消设置 ANTHROPIC_API_KEY 环境变量，或执行 claude /logout 后重新登录，并在 API Key 授权时选择 “No”。',
  'RAW::? Unset the apiKeyHelper setting.': '？请取消 apiKeyHelper 设置。',
  'RAW::? claude /logout to sign out of claude.ai.': '？请执行 claude /logout 退出 claude.ai。',
  'RAW:: environment variable.': ' 环境变量。',
  'RAW:: will impact performance (': ' 会影响性能（',
  'RAW:: chars > ': ' 字符 > ',
  'RAW::Large cumulative agent descriptions will impact performance (~': '累计的 Agent 描述过大，会影响性能（约 ',
  'RAW::Working with HTML/CSS? Install the frontend-design plugin:\n': '正在处理 HTML/CSS？安装 frontend-design 插件：\n',
  'RAW::Working with Vercel? Install the vercel plugin:\n': '正在处理 Vercel？安装 vercel 插件：\n',
};

module.exports = {
  ...spinnerVerbMap,
  ...rawKeywordMap,
  // ========== /config 配置面板 ==========
  'Auto-compact': '自动压缩',
  'Show tips': '显示提示',
  'Reduce motion': '减少动画效果',
  'Thinking mode': '深度思考模式',
  '`Fast mode (${Ok} only)`': '`快速模式（仅限 ${Ok}）`',
  'Prompt suggestions': '提示词建议',
  'Rewind code (checkpoints)': '代码回退（检查点）',
  'Verbose output': '详细输出',
  'Terminal progress bar': '终端进度条',
  'Show turn duration': '显示每轮耗时条',
  'Default permission mode': '默认权限模式',
  'Respect .gitignore in file picker': '文件选择器中遵守 .gitignore 规则',
  'Always copy full response (skip /copy picker)': '始终复制完整回复（跳过 /copy 选择器）',
  'Auto-update channel': '自动更新频道',
  Theme: '主题',
  Notifications: '通知',
  'Output style': '输出风格',
  Language: '语言',
  'Editor mode': '编辑器模式',
  Model: '模型',
  'Auto-install IDE extension': '自动安装 IDE 扩展',
  'Enable Claude in Chrome by default': '默认启用 Chrome 中的 Claude',
  'Claude in Chrome enabled by default': '默认启用 Chrome 中的 Claude',
  'Auto-connect to IDE (external terminal)': '自动连接 IDE（外部终端）',
  'Show PR status footer': '显示 PR 状态栏',
  'Auto-connect to IDE (external terminal)': '自动连接 IDE（外部终端）',
  'Show PR status footer': '显示 PR 状态栏',

  Usage: '使用量',
  Status: '状态',
  Config: '配置',
  'Search settings...': '搜索设置',
  ' more above': ' 条在上方',
  ' more below': ' 条在下方',
  'more below': '条在下方',
  'Esc to cancel': 'Esc 取消',
  'Edit and press Enter to retry, or Esc to cancel': '编辑后按 Enter 重试，或按 Esc 取消',
  'Enter to submit · Esc to cancel': 'Enter 提交 · Esc 取消',
  'Tab to toggle · Enter to confirm · Esc to cancel': 'Tab 切换 · Enter 确认 · Esc 取消',
  'Enter to copy link · Esc to cancel': 'Enter 复制链接 · Esc 取消',
  'Press ↑↓ to navigate, Enter to select, Esc to cancel': '↑↓ 导航 · Enter 选择 · Esc 取消',
  'Esc to cancel · r to cycle dates': 'Esc 取消 · r 切换日期',
  '· Esc to cancel': '· Esc 取消',
  'Enter to confirm · Esc to cancel': 'Enter 确认 · Esc 取消',
  '/usage is only available for subscription plans.': '/usage 仅适用于订阅计划',

  // ========== 主要 UI ==========
  'Welcome back!': '欢迎回来!',
  'API Usage Billing': 'API 使用计费',
  'Tips for getting started': '入门技巧',
  'Run /init to create a CLAUDE.md file with instructions for Claude': '运行 /init 来创建一个 CLAUDE.md 文件，包含 Claude 的使用说明',
  'Recent activity': '最近活动记录',
  'No recent activity': '暂无最近活动记录',
  'create a util logging.py that...': '创建一个工具文件 logging.py，用于...',
  'Initialize a new CLAUDE.md file with codebase documentation': '初始化一个新的 CLAUDE.md 文件，并写入代码库的相关文档说明',
  'Review changed code for reuse, quality, and efficiency, then fix any issues found.': '检查修改过的代码，评估其可复用性、代码质量和执行效率，然后修复发现的所有问题。',
  'Add a new working directory': '添加一个新的工作目录',
  'Clear conversation history and free up context': '清除对话历史记录，释放上下文空间',
  'Set the prompt bar color for this session': '设置本次会话的提示栏颜色',
  'Clear conversation history but keep a summary in context. Optional: /compact [instructions for summarization]': '清除对话历史记录，但在上下文中保留一份摘要。可选：/compact [摘要的自定义指令]',
  'Open config panel': '设置',
  "Copy Claude's last response to clipboard (or /copy N for the Nth-latest)": '复制 Claude 的最后一条回复到剪贴板（或用 /copy N 复制第 N 条最新回复）',
  'Show the total cost and duration of the current session': '显示当前会话的总费用和持续时间',
  'Continue the current session in Claude Desktop': '在 Claude Desktop 中继续当前会话',
  'View uncommitted changes and per-turn diffs': '查看未提交的更改和每轮对话的差异',
  'Diagnose and verify your Claude Code installation and settings': '诊断并验证 Claude Code 的安装和设置',
  'Configure the Advisor Tool to consult a stronger model for guidance at key moments during a task': '配置 Advisor 工具，使其在任务关键时刻向更强模型寻求指导',
  'Manage authentication': '管理认证',
  'Configure the auto-compact window size': '配置自动压缩窗口大小',
  'Spawn a remote Claude Code session that monitors and autofixes the current PR': '启动远程 Claude Code 会话，监控并自动修复当前 PR',
  'Inject bridge failure states for manual recovery testing': '注入桥接故障状态，用于手动恢复测试',
  'Toggle brief-only mode': '切换仅简洁模式',
  'Start a new session with empty context; previous session stays on disk (resumable with /resume)': '开启一个空上下文的新会话；之前的会话仍保存在磁盘上（可用 /resume 恢复）',
  'Inspect auto mode classifier configuration': '查看自动模式配置',
  'Check the health of your Claude Code auto-updater. Note: The workspace trust dialog is skipped and stdio servers from .mcp.json are spawned for health checks. Only use this command in directories you trust.': '检查 Claude Code 自动更新器状态。注意：此命令会跳过工作区信任对话框，并为健康检查启动 .mcp.json 中的 stdio 服务器。仅在你信任的目录中使用。',
  'Install Claude Code native build. Use [target] to specify version (stable, latest, or specific version)': '安装 Claude Code 原生版。可用 [target] 指定 stable、latest 或具体版本。',
  'Check for updates and install if available': '检查更新并在有可用版本时安装',
  'Set up a long-lived authentication token (requires Claude subscription)': '设置长期认证令牌（需要 Claude 订阅）',
  'Set effort level for model usage': '设置模型使用的努力等级',
  'Exit the REPL': '退出 REPL',
  'Export the current conversation to a file or clipboard': '将当前对话导出到文件或剪贴板',
  'Submit feedback about Claude Code': '提交关于 Claude Code 的反馈',
  'List all files currently in context': '列出当前上下文中的所有文件',
  'Toggle focus view (show only your prompt, a tool summary, and the final response)': '切换专注视图（仅显示你的提示词、工具摘要和最终回复）',
  'Dump the JS heap to ~/Desktop': '将 JS 堆转储到 ~/Desktop',
  'Show help and available commands': '显示帮助信息和可用命令',
  'View hook configurations for tool events': '查看工具事件的钩子配置',
  'Manage IDE integrations and show status': '管理 IDE 集成并显示状态',
  'Set up Claude GitHub Actions for a repository': '为仓库配置 Claude GitHub Actions',
  'Install the Claude Slack app': '安装 Claude Slack 应用',
  'Sign in to your Anthropic account': '登录 Anthropic 账号',
  'Sign in with your Anthropic account': '使用 Anthropic 账号登录',
  'List, create, and delete recurring loops and stop-hooks': '列出、创建和删除定时循环与停止钩子',
  'Log out from your Anthropic account': '从 Anthropic 账号退出登录',
  'Sign out from your Anthropic account': '退出 Anthropic 账号',
  'Show authentication status': '显示认证状态',
  'Manage MCP servers': '管理 MCP 服务器',
  'Edit Claude memory files': '编辑 Claude 记忆文件',
  'Discover Claude Code features through quick interactive lessons': '通过快速交互式课程了解 Claude Code 功能',
  'View and update your privacy settings': '查看并更新你的隐私设置',
  'Show options when rate limit is reached': '在达到速率限制时显示可选操作',
  'Generate a one-line session recap now': '立即生成一行会话摘要',
  'Configure the default remote environment for teleport sessions': '配置 teleport 会话的默认远程环境',
  'Reconfigure AWS Bedrock authentication, region, or model pins': '重新配置 AWS Bedrock 的认证、区域或模型固定设置',
  'Reconfigure Google Vertex AI authentication, project, region, or model pins': '重新配置 Google Vertex AI 的认证、项目、区域或模型固定设置',
  'Set a session-only Stop hook with a quick prompt': '用简短提示词设置仅限本会话的 Stop 钩子',
  'Resume a Claude Code session from claude.ai': '从 claude.ai 恢复 Claude Code 会话',
  'Toggle automemory off/on for this session': '为本次会话切换自动记忆开/关',
  'Set the terminal UI renderer (default | fullscreen)': '设置终端 UI 渲染模式（default | fullscreen）',
  'Switch to the latest version (conversation continues)': '切换到最新版本（对话会继续）',
  'Print the version this session is running (not what autoupdate downloaded)': '显示当前会话正在运行的版本（不是自动更新下载的版本）',
  'Toggle voice mode': '切换语音模式',
  'Setup Claude Code on the web (requires connecting your GitHub account)': '在网页端设置 Claude Code（需要连接你的 GitHub 账号）',
  'Show QR code to download the Claude mobile app': '显示二维码以下载 Claude 移动端应用',
  'Manage allow & deny tool permission rules': '管理工具的允许和拒绝权限规则',
  'Enable plan mode or view the current session plan': '启用计划模式或查看当前会话计划',
  'Manage Claude Code plugins': '管理 Claude Code 插件',
  'View release notes': '查看发布说明',
  'Activate pending plugin changes in the current session': '在当前会话中激活待生效的插件更改',
  'Rename the current conversation': '重命名当前对话',
  'Resume a previous conversation': '恢复之前的对话',
  'Restore the code and/or conversation to a previous point': '将代码和/或对话恢复到之前的某个节点',
  'List available skills': '列出可用的技能',
  'Show your Claude Code usage statistics and activity': '显示 Claude Code 的使用统计和活动记录',
  'Show Claude Code status including version, model, account, API connectivity, and tool statuses': '显示 Claude Code 状态，包括版本、模型、账号、API 连接和工具状态',
  'Order Claude Code stickers': '订购 Claude Code 贴纸',
  'List and manage background tasks': '列出并管理后台任务',
  'Install Shift+Enter key binding for newlines': '安装 Shift+Enter 换行快捷键绑定',
  'Change the theme': '更改主题',
  'Upgrade to Max for higher rate limits and more Opus': '升级到 Max 计划以获得更高速率限制和更多 Opus 用量',
  'Show plan usage limits': '显示计划用量限制',
  'Toggle between Vim and Normal editing modes': '在 Vim 和普通编辑模式之间切换',
  'Research and plan a large-scale change, then execute it in parallel across 5\u201330 isolated worktree agents that each open a PR.':
    '研究并规划大规模变更，然后通过 5-30 个独立的 worktree Agent 并行执行，每个 Agent 各自创建一个 PR',
  'Build apps with the Claude API or Anthropic SDK.\nTRIGGER when: code imports `anthropic`/`@anthropic-ai/sdk`/`claude_agent_sdk`, or user asks to use Claude API, Anthropic SDK, or Agent SDK.\nDO NOT TRIGGER when: code imports `openai`/other AI SDK, general programming, or ML/data-science tasks.':
    '使用 Claude API 或 Anthropic SDK 构建应用。\n触发条件：代码导入 `anthropic`/`@anthropic-ai/sdk`/`claude_agent_sdk`，或用户要求使用 Claude API、Anthropic SDK 或 Agent SDK。\n不触发条件：代码导入 `openai`/其他 AI SDK、通用编程或机器学习/数据科学任务',
  'Enable debug logging for this session and help diagnose issues': '为本次会话启用调试日志以帮助诊断问题',
  'Generate a report analyzing your Claude Code sessions': '生成分析 Claude Code 会话的报告',
  'Run a prompt or slash command on a recurring interval (e.g. /loop 5m /foo, defaults to 10m)': '按固定间隔重复执行提示词或斜杠命令（例如 /loop 5m /foo，默认间隔 10 分钟）',
  'Get comments from a GitHub pull request': '获取 GitHub Pull Request 的评论',
  'Review a pull request': '审查 Pull Request',
  'Complete a security review of the pending changes on the current branch': '对当前分支的待提交更改进行安全审查',
  "Set up Claude Code's status line UI": '配置 Claude Code 的状态栏 UI',

  'Config dialog dismissed': '配置对话框已关闭',
  'shift+tab to cycle': '按 shift+tab 切换选项',
  'Manage agent configurations': '管理 Agent 配置',
  'Create a branch of the current conversation at this point': '在此处创建当前对话的分支',
  'Ask a quick side question without interrupting the main conversation': '提问一个临时问题，不打断主对话',
  'Claude in Chrome (Beta) settings': 'Chrome 中的 Claude（测试版）设置',
  'Visualize current context usage as a colored grid': '以彩色网格可视化当前上下文用量',
  'Use this skill to configure the Claude Code harness via settings.json. Automated behaviors ("from now on when X", "each time X", "whenever X", "before/after X") require hooks configured in settings.json - the harness executes these, not Claude, so memory/preferences cannot fulfill them. Also use for: permissions ("allow X", "add permission", "move permission to"), env vars ("set X=Y"), hook troubleshooting, or any changes to settings.json/settings.local.json files. Examples: "allow npm commands", "add bq permission to global settings", "move permission to user settings", "set DEBUG=true", "when claude stops show X". For simple settings like theme/model, use Config tool.':
    '使用此技能通过 settings.json 配置 Claude Code 运行环境。自动化行为（"从现在起每当 X"、"每次 X"、"每当 X"、"在 X 之前/之后"）需要在 settings.json 中配置钩子——由运行环境执行，而非 Claude，因此记忆/偏好设置无法实现这类需求。也适用于：权限管理（"允许 X"、"添加权限"、"移动权限至"）、环境变量（"设置 X=Y"）、钩子排查，或对 settings.json/settings.local.json 的任何修改。示例："允许 npm 命令"、"将 bq 权限添加到全局设置"、"将权限移至用户设置"、"设置 DEBUG=true"、"当 Claude 停止时显示 X"。如需修改主题/模型等简单设置，请使用 Config 工具。',
  '`Toggle fast mode (${Ok} only)`': '`切换快速模式（仅限 ${Ok}）`',
  '`Set the AI model for Claude Code (currently ${oj(Z5())})`': '`设置 Claude Code 的 AI 模型（当前模型：${oj(Z5())}）`',
  '`Tip: ${effectiveTip}`': '`提示：${effectiveTip}`',
  '`Next: ${nextTask.subject}`': '`下一步：${nextTask.subject}`',

  // ========== cute-claude-hooks 独有条目 ==========
  'Commit, push, and open a PR': '提交、推送并创建 PR',
  'Create a git commit': '创建一个 Git 提交',
  'Create verifier skill(s) for automated verification of code changes': '创建验证器技能以用于自动验证代码更改',
  'Install the Claude GitHub App': '安装 Claude GitHub App',
  'Opening browser to install the Claude GitHub App…': '正在打开浏览器以安装 Claude GitHub App…',
  "1. Install the Claude GitHub App if you haven't already": '1. 如果你还没安装 Claude GitHub App，请先完成安装',
  '2. Your workflow file was kept unchanged': '2. 你的工作流文件保持不变',
  '3. API key is configured and ready to use': '3. API Key 已配置完成，可以立即使用',
  '1. A pre-filled PR page has been created': '1. 已为你创建预填好的 PR 页面',
  "3. Merge the PR to enable Claude PR assistance": '3. 合并该 PR 后即可启用 Claude PR 助手',
  'Open or create your keybindings configuration file': '打开或创建快捷键配置文件',
  'Connect this terminal for remote-control sessions': '连接此终端以进行远程控制会话',
  'Configure the advisor model': '配置顾问模型',
  'Deprecated: use /config to change output style': '已弃用：使用 /config 更改输出风格',
  'Configure extra usage to keep working when limits are hit': '配置额外用量，在达到限制后继续工作',
  'Skip this picker in the future': '以后跳过此选择器（可通过 /config 恢复）',
  'Toggle a searchable tag on the current session': '切换当前会话的可搜索标签',
  'Show current context usage': '显示当前上下文用量',
  'Show total cost and duration of the current session': '显示当前会话的总费用和持续时间',
  'Install Claude Code native build': '安装 Claude Code 原生构建',
  'Show orange progress bar at bottom (default: true)': '在底部显示橙色进度条（默认：true）',
  'Color theme for the UI': '界面颜色主题',
  'Show detailed debug output': '显示详细调试输出',
  'Preferred notification channel': '首选通知渠道',
  'Custom model': '自定义模型',
  'Override the default model': '覆盖默认模型',
  'Auto-compact when context is full': '当上下文满时自动压缩',
  'Enable auto-memory': '启用自动记忆',
  'Enable background memory consolidation': '启用后台记忆整合',
  'Enable file checkpointing for code rewind': '启用文件检查点以支持代码回退',
  'Enable Remote Control for all sessions': '为所有会话启用远程控制',
  'Show one guided-tour tooltip and wait for the user to click Next': '显示一个引导提示并等待用户点击下一步',
  'Run a command with a time limit': '在限时内运行命令',
  'Create, update, list, or run scheduled remote agents (triggers) that execute on a cron schedule.': '创建、更新、列出或运行按 cron 计划执行的定时远程代理（触发器）',
  'Duration to sleep (seconds or with suffix like 5s, 2m, 1h)': '休眠持续时间（秒或带后缀如 5s、2m、1h）',
  'Provide an explanation of a shell command': '解释 Shell 命令',
  'Use /clear to start fresh when switching topics and free up context': '切换话题时可使用 /clear 重新开始，并释放上下文空间',
  "Use /btw to ask a quick side question without interrupting Claude's current work": '使用 /btw 提一个临时小问题，不会打断 Claude 当前正在处理的主任务',
  'Use /theme to change the color theme': '使用 /theme 更改颜色主题',
  'Use /memory to view and manage Claude memory': '使用 /memory 查看并管理 Claude 记忆',
  'Use /statusline to set up a custom status line that will display beneath the input box': '使用 /statusline 配置自定义状态栏，它会显示在输入框下方',
  'Use /config to change your default permission mode (including Plan Mode)': '使用 /config 修改默认权限模式（包含 Plan Mode）',
  'Use git worktrees to run multiple Claude sessions in parallel.': '使用 git worktrees 并行运行多个 Claude 会话',
  'Press Shift+Enter to send a multi-line message': '按 Shift+Enter 发送多行消息',
  'Press Option+Enter to send a multi-line message': '按 Option+Enter 发送多行消息',
  'Run /terminal-setup to enable Shift+Enter for new lines': '运行 /terminal-setup 启用 Shift+Enter 换行',
  'Run /terminal-setup to enable Option+Enter for new lines': '运行 /terminal-setup 启用 Option+Enter 换行',
  'Determining': '分析中',
  'Channeling': '处理中',
  'Thinking': '思考中',
  'Considering': '斟酌中',
  'Computing': '计算中',
  'Working': '处理中',
  'Start with small features or bug fixes, tell Claude to propose a plan, and verify its suggested edits': '建议从小功能或小型缺陷修复开始，让 Claude 先给出计划，再验证它建议的修改',
  'Use Plan Mode to prepare for a complex request before making changes. Press ': '处理复杂请求前，可先使用 Plan Mode 做准备。按 ',
  ' twice to enable.': ' 两次即可启用。',
  'Running multiple Claude sessions? Use /color and /rename to tell them apart at a glance.': '同时运行多个 Claude 会话？可以用 /color 和 /rename 快速区分它们。',
  'Run /terminal-setup to enable convenient terminal integration like Shift + Enter for new line and more': '运行 /terminal-setup 启用更方便的终端集成，例如 Shift + Enter 换行等功能',
  'Run /terminal-setup to enable convenient terminal integration like Option + Enter for new line and more': '运行 /terminal-setup 启用更方便的终端集成，例如 Option + Enter 换行等功能',
  'Try setting environment variable COLORTERM=truecolor for richer colors': '可尝试设置环境变量 COLORTERM=truecolor，以获得更丰富的颜色显示',
  'Set CLAUDE_CODE_USE_POWERSHELL_TOOL=1 to enable the PowerShell tool (preview)': '设置 CLAUDE_CODE_USE_POWERSHELL_TOOL=1 以启用 PowerShell 工具（预览版）',
  'Hit Enter to queue up additional messages while Claude is working.': '当 Claude 正在工作时，按 Enter 可继续排队发送更多消息。',
  'Send messages to Claude while it works to steer Claude in real-time': '在 Claude 工作时继续发送消息，以便实时调整它的处理方向',
  'Ask Claude to create a todo list when working on complex tasks to track progress and remain on track': '处理复杂任务时，可以让 Claude 创建待办清单来跟踪进度并保持方向一致',
  'Connect Claude to your IDE · /ide': '将 Claude 连接到你的 IDE · /ide',
  'Run /install-github-app to tag @claude right from your Github issues and PRs': '运行 /install-github-app，即可直接在 GitHub 的 Issue 和 PR 中 @claude',
  'Run /install-slack-app to use Claude in Slack': '运行 /install-slack-app，在 Slack 中使用 Claude',
  'Use /permissions to pre-approve and pre-deny bash, edit, and MCP tools': '使用 /permissions 预先配置 bash、编辑和 MCP 工具的允许与拒绝规则',
  'Did you know you can drag and drop image files into your terminal?': '你知道吗？可以直接把图片文件拖进终端里使用。',
  'Paste images into Claude Code using control+v (not cmd+v!)': '在 Claude Code 中粘贴图片请使用 control+v（不是 cmd+v！）',
  'Double-tap esc to rewind the conversation to a previous point in time': '双击 esc 可将对话回退到之前的某个时间点',
  'Double-tap esc to rewind the code and/or conversation to a previous point in time': '双击 esc 可将代码和/或对话回退到之前的某个时间点',
  'Run claude --continue or claude --resume to resume a conversation': '运行 claude --continue 或 claude --resume 以恢复之前的对话',
  'Name your conversations with /rename to find them easily in /resume later': '使用 /rename 给对话命名，之后在 /resume 中更容易找到它们',
  'Create skills by adding .md files to .claude/skills/ in your project or ~/.claude/skills/ for skills that work in any project': '通过在项目的 .claude/skills/ 或 ~/.claude/skills/ 中添加 .md 文件来创建 skills，让它们在单个项目或所有项目中生效',
  'Use /agents to optimize specific tasks. Eg. Software Architect, Code Writer, Code Reviewer': '使用 /agents 优化特定任务，例如软件架构师、代码编写者、代码审查者等角色',
  'Use --agent <agent_name> to directly start a conversation with a subagent': '使用 --agent <agent_name> 可直接与某个子代理开始对话',
  'Run Claude Code locally or remotely using the Claude desktop app: clau.de/desktop': '通过 Claude 桌面应用在本地或远程运行 Claude Code：clau.de/desktop',
  'Run tasks in the cloud while you keep coding locally · clau.de/web': '你继续在本地写代码的同时，也可在云端运行任务 · clau.de/web',
  '/mobile to use Claude Code from the Claude app on your phone': '使用 /mobile 可在手机上的 Claude 应用中访问 Claude Code',
  'Your default model setting is Opus Plan Mode. Press ': '你当前的默认模型设置是 Opus Plan Mode。按 ',
  ' to activate Plan Mode and plan with Claude Opus.': ' 以启用 Plan Mode，并使用 Claude Opus 进行规划。',
  'Install the ': '安装 ',
  ' plugin from the': ' 插件，可前往',
  'JetBrains Marketplace:': 'JetBrains 插件市场：',
  ' plugin from the JetBrains Marketplace:': ' 插件，可前往 JetBrains 插件市场安装：',
  'Open the Command Palette (Cmd+Shift+P) and run "Shell Command: Install \'': '打开命令面板（Cmd+Shift+P），执行 “Shell Command: Install \'',
  '\' command in PATH" to enable IDE integration': ' 命令到 PATH” 以启用 IDE 集成',
  'Working with HTML/CSS? Install the frontend-design plugin:\n': '正在处理 HTML/CSS？安装 frontend-design 插件：\n',
  'Working with Vercel? Install the vercel plugin:\n': '正在处理 Vercel？安装 vercel 插件：\n',
  'use subagents': '使用子代理',
  '"fan out subagents"': '"并行派出子代理"',
  'Use /feedback to help us improve!': '使用 /feedback 帮助我们持续改进！',
  'Open the Command Palette (Cmd+Shift+P) and run "Shell Command: Install ': '打开命令面板（Cmd+Shift+P），执行 “Shell Command: Install ',
  ' command in PATH" to enable IDE integration': ' 命令到 PATH” 以启用 IDE 集成',

  // ========== v1.1.0 新增 ==========
  "Copy Claude's last response or a code block to clipboard": "复制 Claude 的最后一条回复或代码块到剪贴板",
  'Create a fork of the current conversation at this point': '在此处创建当前对话的分支副本',
  'Manage hook configurations for tool events': '管理工具事件的钩子配置',
  'Set the AI model for Claude Code': '设置 Claude Code 使用的 AI 模型',
  'Set the output style directly or from a selection menu': '直接设置或从菜单中选择输出风格',

  // ========== 快捷键与过滤提示 ==========
  'Type to filter': '输入以过滤',
  'Type to filter · Enter/↓ select · ↑ tabs · Esc clear': '输入以过滤 · Enter/↓ 选项 · ↑ 切换选项卡 · Esc 清除',
  '(↓ to select)': '(↓ 选择选项)',
  '{shortcut:"Enter/↓",action:"select"}': '{shortcut:"Enter/↓",action:"选择"}',
  '{shortcut:"↑",action:"tabs"}': '{shortcut:"↑",action:"切换选项卡"}',
  '{action:"confirm:no",context:"Settings",fallback:"Esc",description:"clear"}': '{action:"confirm:no",context:"Settings",fallback:"Esc",description:"清除"}',
  '{shortcut:"Enter",action:"save"}': '{shortcut:"Enter",action:"保存"}',
  '{action:"confirm:no",context:"Confirmation",fallback:"Esc",description:"cancel"}': '{action:"confirm:no",context:"Confirmation",fallback:"Esc",description:"取消"}',
  '{shortcut:"Enter",action:"search"}': '{shortcut:"Enter",action:"搜索"}',
  '{action:"select:accept",context:"Settings",fallback:"Space",description:"change"}': '{action:"select:accept",context:"Settings",fallback:"Space",description:"改变"}',
  '{action:"settings:close",context:"Settings",fallback:"Enter",description:"save"}': '{action:"settings:close",context:"Settings",fallback:"Enter",description:"保存"}',
  '{action:"settings:search",context:"Settings",fallback:"/",description:"search"}': '{action:"settings:search",context:"Settings",fallback:"/",description:"搜索"}',
  '{action:"confirm:no",context:"Settings",fallback:"Esc",description:"cancel"}': '{action:"confirm:no",context:"Settings",fallback:"Esc",description:"取消"}',
  '{shortcut:"Esc",action:"cancel"}': '{shortcut:"Esc",action:"取消"}'
}
